"""create table

Revision ID: 0f06f612fc4b
Revises: 
Create Date: 2026-02-07 17:49:53.658028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f06f612fc4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourism',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('DATE_OF_ARRIVAL', sa.Date(), nullable=True),
    sa.Column('VISIT_TYPE', sa.String(length=20), nullable=True),
    sa.Column('TRIP_TYPE', sa.String(length=50), nullable=True),
    sa.Column('HOME_COUNTRY', sa.String(length=50), nullable=True),
    sa.Column('HOME_REGION', sa.String(length=50), nullable=True),
    sa.Column('HOME_CITY', sa.String(length=50), nullable=True),
    sa.Column('GOAL', sa.String(length=50), nullable=True),
    sa.Column('GENDER', sa.String(length=10), nullable=True),
    sa.Column('AGE', sa.String(length=50), nullable=True),
    sa.Column('INCOME', sa.String(length=50), nullable=True),
    sa.Column('DAYS_CNT', sa.Integer(), nullable=True),
    sa.Column('VISITORS_CNT', sa.Integer(), nullable=True),
    sa.Column('SPENT', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tourism')
    # ### end Alembic commands ###
